#- docker-compose.yaml

version: '3'

services:

    shotgun-event:
        container_name: Shotgun-Event

        image: shotgun-event
        restart: unless-stopped

        environment:
            PYTHONPATH: /usr/src/app/site-packages

        volumes:
            - /home/shotgunEvents/shotgunEventDaemon.conf:/usr/src/app/shotgunEvents/src/shotgunEventDaemon.conf
            - /home/shotgunEvents/site-packages:/usr/src/app/site-packages
            - /home/shotgunEvents/plugins:/usr/src/app/shotgunEvents/plugins
            - /home/shotgunEvents/logs:/usr/src/app/shotgunEvents/logs
